// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/welcome","name":"welcome","icon":"smile","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/base","name":"base","icon":"appstore","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/base/department","name":"department","access":"hasPrivilege","parentId":"4","id":"5"},"6":{"path":"/base/article","name":"article","access":"hasPrivilege","parentId":"4","id":"6"},"7":{"path":"/base/fullsearch","name":"fullsearch","access":"hasPrivilege","parentId":"4","id":"7"},"8":{"path":"/system","name":"system","icon":"crown","parentId":"ant-design-pro-layout","id":"8"},"9":{"path":"/system/admin","name":"admin","access":"hasPrivilege","parentId":"8","id":"9"},"10":{"path":"/system/loginLog","name":"loginLog","access":"hasPrivilege","parentId":"8","id":"10"},"11":{"path":"/system/onlineUser","name":"onlineUser","access":"hasPrivilege","parentId":"8","id":"11"},"12":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"12"},"13":{"path":"*","layout":false,"id":"13"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'4': React.lazy(() => import( './EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__base__department__index" */'@/pages/base/department/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__base__article__index" */'@/pages/base/article/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__base__fullsearch__index" */'@/pages/base/fullsearch/index.tsx')),
'8': React.lazy(() => import( './EmptyRoute')),
'9': React.lazy(() => import(/* webpackChunkName: "p__system__admin__index" */'@/pages/system/admin/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__system__loginLog__index" */'@/pages/system/loginLog/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__system__onlineUser__index" */'@/pages/system/onlineUser/index.tsx')),
'12': React.lazy(() => import( './EmptyRoute')),
'13': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'D:/Github/FilmArticleManage/front/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'D:/Github/FilmArticleManage/front/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
