// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'C:/Users/zz153/Desktop/FilmArticleManage/front/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import AppstoreOutlined from 'C:/Users/zz153/Desktop/FilmArticleManage/front/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
import CrownOutlined from 'C:/Users/zz153/Desktop/FilmArticleManage/front/node_modules/@ant-design/icons/es/icons/CrownOutlined';
export default { SmileOutlined, AppstoreOutlined, CrownOutlined };
